services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    command: ["mongod","--replSet","rs0","--keyFile","/etc/mongo-keyfile"]
    networks:
      - mongodb_network

    healthcheck:
      test:
        - CMD
        - mongosh
        - 'mongodb://localhost:27017/admin'
        - '--eval=db.hello().isWritablePrimary || quit(1)'
      interval: 5s
      retries: 3
      timeout: 5s
    volumes:
      - mongodb_data:/data/db
      - ./mongo-keyfile:/etc/mongo-keyfile:ro

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - 8081:8081

    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USERNAME}:${DB_PASSWORD}@mongodb:27017/files?authSource=admin&replicaSet=rs0
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - mongodb_network

  web:
    build: .
    ports:
      - 3000:3000
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - MONGODB_URI=${MONGODB_URI}
      - DB_HOST=mongodb
      - DB_PORT=27017
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://0.0.0.0:3000/health"]
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - mongodb_network
    volumes:
      - .:/app
      -  /app/node_modules

  redis:
    image: redis:8.8.2
    container_name: message_broker
    command: redis-server --appendonly yes 
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - mongodb_network
    volumes:
      - redis_broker_data:/data

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    container_name: object_storage
    command: server --console-address ":9001" /data
    ports:
    - 9001:9001
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - mongodb_network
    volumes:
      - minio_data:/data
  
  worker:
    build: .
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - MONGODB_URI=${MONGODB_URI}
      - DB_HOST=mongodb
      - DB_PORT=27017
    entrypoint: ["node"]
    command: ["./worker.js"]
    depends_on:
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    networks:
      - mongodb_network
    volumes:
      - .:/app
      -  /app/node_modules

networks:
  mongodb_network:

volumes:
  mongodb_data:
  redis_broker_data:
  minio_data: